name: shinyab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24369
title: mePhoto by Shinya B
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c9bc7'
    - '#090909'
    - '#3b333e'
    - '#d3c9bf'
    - '#9e7b74'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
