name: shinyab
favicon: null
layout_spectrum: 0.11251341574825346
typography_spectrum: 0.9406612140592188
title: Things I see
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6853945881593972
  lightness: 0.47208376904018223
  saturation: 0.4434649939648807
  rhythmicContrast: 0.31043915543705225
purpose: []
