name: shinyab
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9406612140592188
title: Things I see
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c9bc7'
    - '#090909'
    - '#3b333e'
    - '#d3c9bf'
    - '#9e7b74'
  brandStrength: 1
  lightness: 0.47208376904018223
  saturation: 0
  rhythmicContrast: 0.31043915543705225
purpose: []
